#!/bin/bash

# Node related modules

# Install necessary deps for nvm
sudo apt install build-essential libssl-dev -y

# Install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash

# Install Bun
curl -fsSL https://bun.sh/install | bash 
