#!/bin/bash

. ~/.env

sudo apt install git ssh

AUTHORIZATION="Authorization: token $GITHUB_TOKEN"

curl -LO \
  -H  $AUTHORIZATION \
  -H "Accept: application/vnd.github.v3.raw" \
  https://api.github.com/repos/Billocap/.dotfiles/contents/setup-ssh

bash ~/setup-ssh github

. ~/.keys.temp

HOST=$(hostname)
TITLE="$USER@$HOST"
KEY=$(cat $PUBLIC_FILE)

curl -L \
  -X POST \
  -H "Accept: application/vnd.github+json" \
  -H $AUTHORIZATION \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/user/keys \
  -d "{\"title\":\"$TITLE\", \"key\":\"$KEY\"}"

git clone git@github.com:Billocap/.dotfiles.git ~/.dotfiles

ln -s ~/.dotfiles/.gitconfig ~/.gitconfig

rm ~/.keys.temp

bash ~/.dotfiles/setup

