#!/bin/bash

# Necessary variables
WORKDIR=~

[ ! -d $WORKDIR ] && WORKDIR=$(pwd)

HOME_FOLDER=$WORKDIR/.dotfiles
MODULES_FOLDER=$HOME_FOLDER/modules
CONFIGS_FOLDER=$HOME_FOLDER/configs
FONTS_FOLDER=$HOME_FOLDER/fonts
MISC_FOLDER=$HOME_FOLDER/misc
DISTRO_FOLDER=$HOME_FOLDER/distros
TOOLS_FOLDER=$HOME_FOLDER/tools

ln -s $CONFIGS_FOLDER/.gitconfig $WORKDIR/.gitconfig

SELECTED_DISTRO=$1

[ -z $SELECTED_DISTRO ] && SELECTED_DISTRO="any"

DISTRO_INSTALLER=$DISTRO_FOLDER/$SELECTED_DISTRO.sh

[ ! -f $DISTRO_INSTALLER ] && DISTRO_INSTALLER=$DISTRO_FOLDER/any.sh

. $DISTRO_INSTALLER

sudo cp $FONTS_FOLDER/figlet/* /usr/share/figlet

case $SELECTED_DISTRO in
  "arch") install;;
  *) . $TOOLS_FOLDER/screen.sh "install";;
esac
