#!/bin/bash

. ~/.env

AUTHORIZATION="Authorization: token $GITHUB_TOKEN"

sudo apt install git figlet -y

git clone "https://github.com/xero/figlet-fonts.git"

mv ~/figlet-fonts/* /usr/share/figlet

curl -LO \
  -H  "$AUTHORIZATION" \
  -H "Accept: application/vnd.github.v3.raw" \
  https://api.github.com/repos/Billocap/.dotfiles/contents/screen

curl -LO \
  -H  "$AUTHORIZATION" \
  -H "Accept: application/vnd.github.v3.raw" \
  https://api.github.com/repos/Billocap/.dotfiles/contents/install

. ~/screen "bash install"

