#!/bin/bash

[ -f ~/install ] && rm ~/install

sudo apt install zsh
curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
sudo usermod --shell $(which zsh) $USER

[ -f ~/.oh-my-zsh/themes/plain.zsh-theme ] && rm ~/.oh-my-zsh/themes/plain.zsh-theme
ln -s ~/.dotfiles/themes/plain.zsh-theme ~/.oh-my-zsh/themes/plain.zsh-theme

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

[ -f ~/.zshrc ] && rm ~/.zshrc
ln -s ~/.dotfiles/.zshrc ~/.zshrc

sudo apt install vim build-essential libssl-dev 
