#!/bin/bash

[ -f ~/install ] && rm ~/install

sudo apt install zsh -y
curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
sudo usermod --shell $(which zsh) $USER

[ -f ~/.oh-my-zsh/themes/plain.zsh-theme ] && rm ~/.oh-my-zsh/themes/plain.zsh-theme
ln -s ~/.dotfiles/themes/plain.zsh-theme ~/.oh-my-zsh/themes/plain.zsh-theme

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/supercrabtree/k ~/.oh-my-zsh/custom/plugins/k

[ -f ~/.zshrc ] && rm ~/.zshrc
ln -s ~/.dotfiles/.zshrc ~/.zshrc

sudo apt install vim -y

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

ln -s ~/.dotfiles/.vimrc ~/.vimrc

vim +PlugInstall +qall

sudo apt install build-essential libssl-dev -y

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash
